# Generated by Django 6.0.2 on 2026-03-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название статьи",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Контент статьи", verbose_name="Контент"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Изображение статьи",
                        upload_to="blog/photo",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True,
                        help_text="Дата создания статьи",
                        null=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        blank=True,
                        help_text="Дата обновления статьи",
                        null=True,
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "publication_status",
                    models.BooleanField(
                        default=False,
                        help_text="Статус публикации статьи",
                        verbose_name="Статус публикации",
                    ),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество просмотров статьи",
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
