# Generated by Django 6.0.2 on 2026-03-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_publication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="publication_status",
            field=models.BooleanField(
                default=False,
                help_text="Статус публикации статьи",
                verbose_name="Статус публикации",
            ),
        ),
    ]
