# Generated by Django 6.0.2 on 2026-03-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
